# 1. Automatically create instances for component database claims
# 
# Pros:
#   - Simplest declaration
#   - Doesn't require explicit database matching
# Cons:
#   - Not obvious how you'd change DB size after first deployment

providers:
  - type: database
    provider: do-personal

components:
  account/component:
    source: file:./

---

# 2. Automatically creates a single database instance that is to be 
#    shared by all matching claims

providers:
  - type: database
    provider: do-personal
    shared: true

components:
  account/component:
    source: file:./

---

# 3. If a database is created implicitly, you still may need to edit
#    the database size at a later date:
  
providers:
  - type: database
    provider: do-personal

databases:
  account/component/db-name:
    provider: do-personal
    type: postgres:13
    size: some-size-slug

components:
  account/component:
    source: file:./
    databases:
      db-name:
        instance: account/component/db-name

---

# 4. Naming conventions for generated DBs are different for shared instances
  
providers:
  - type: database
    provider: do-personal
    shared: true

databases:
  postgres/13:
    provider: do-personal
    type: postgres:13
    size: some-size-slug

components:
  account/component:
    source: file:./
    databases:
      db-name:
        instance: postgres/13

---

# 5. Use an existing database

databases:
  existing-instance:
    url: postgresql://username:password@host:port

components:
  account/component:
    source: file:./

    databases:
      main:
        instance: existing-instance

---

# 6. Use an existing schema

databases:
  existing-instance:
    url: postgresql://username:password@host:port

components:
  account/component:
    source: file:./

    databases:
      main:
        instance: existing-instance
        schema: existing-schema

---

# 7. Use an existing user

databases:
  existing-instance:
    url: postgresql://username:password@host:port

components:
  account/component:
    source: file:./

    databases:
      main:
        instance: existing-instance
        schema: existing-schema
        username: existing-user
        password: existing-password