name: dthor-test

resources:
  dns_zone:
    type: dnsZone
    provider: cloudflare
    name: dthor.architect.io
  vpc:
    type: vpc
    region: nyc1
    provider: do-personal
  kubernetes_cluster:
    type: kubernetesCluster
    vpc: ${{ resources.vpc.id }}
    provider: do-personal
    version: 1.24.1
    node_pools:
      - count: 3
        size: size-slug

mutators:
  - when:
      type: database
    node:
      provider: do-personal
      inputs:
        vpc: ${{ resources.vpc.id }}
  - when:
      type: dnsRecord
    node:
      provider: cloudflare
      inputs:
        zone: ${{ resources.dns_zone.id }}
  - when:
      type: dockerBuild
    node:
      provider: ${{ resources.kubernetes_cluster.provider }}
      inputs:
        registry: registry.architect.io
        tag: latest
  - node:
      provider: ${{ resources.kubernetes_cluster.provider }}

components:
  accounts/legacy:
    services:
      main:
        url: https://internal.mydomain.com

  account/dependency:
    source: registry.architect.io/account/dependency:latest
    services:
      api:
        scaling:
          replicas: 2
          min_replicas: 2
          max_replicas: 4
  
  account/component:
    source: file:./component.yml

    databases:
      main:
        dsn: ${{ databases.new.url }}
      existing:
        dsn: ${{ databases.existing.url }}/
      
