variables:
  gcpAccount:
    type: arcctlAccount
    description: Name of your registered GCP account.
    provider: gcp
  region:
    type: region
    description: Region to put resources in
    arcctlAccount: ${{ variables.gcpAccount }}
  dnsZone:
    type: string
    description: Name of DNS zone for DNS records. This zone must already exist within GCP.

resources:
  vpc:
    type: vpc
    name: ${{ datacenter.name }}-dc
    account: ${{ variables.gcpAccount }}
    region: ${{ variables.region }}

environment:
  hooks:
    - when:
        type: deployment
      namespace: ${{ environment.name }}
      labels:
        region: ${{ variables.region }}
      account: ${{ variables.gcpAccount }}
    - when:
        type: ingressRule
      resources:
        dnsRecord:
          type: dnsRecord
          account: ${{ variables.gcpAccount }}
          dnsZone: ${{ variables.dnsZone }}
          subdomain: ${{ this.inputs.subdomain }}
          recordType: A
          content: ${{ this.outputs.loadBalancerHostname }}
      dnsZone: ${{ variables.dnsZone }}
      namespace: ${{ environment.name }}
    - when:
        type: service
      namespace: ${{ environment.name }}
      labels:
        region: ${{ variables.region }}
    - when:
        type: database
        databaseType: postgres
      resources:
        db-cluster:
          type: databaseCluster
          account: ${{ variables.gcpAccount }}
          name: ${{ this.name }}
          databaseSize: db-f1-micro
          databaseType: ${{ this.inputs.databaseType }}
          databaseVersion: ${{ this.inputs.databaseVersion }}
          region: ${{ variables.region }}
          vpc: ${{ resources.vpc.id }}
      accounts:
        db-cluster:
          provider: postgres
          name: ${{ this.name }}-db-cluster
          credentials:
            host: ${{ this.resources.db-cluster.host }}
            port: ${{ this.resources.db-cluster.port }}
            username: ${{ this.resources.db-cluster.username }}
            password: ${{ this.resources.db-cluster.password }}
            database: postgres
      account: ${{ this.accounts.db-cluster.id }}
    - account: ${{ variables.gcpAccount }}
      namespace: ${{ environment.name }}
