secrets:
  account: local

variables:
  gcpAccount:
    type: arcctlAccount
    description: Name of your registered GCP account.
    provider: gcp
  region:
    type: region
    description: Region to put resources in
    arcctlAccount: ${{ variables.gcpAccount }}
  dnsZone:
    type: string
    description: Name of DNS zone for DNS records

resources:
  vpc:
    type: vpc
    name: gcp-datacenter
    account: ${{ variables.gcpAccount }}
    region: ${{ variables.region }}

environment:
  resources:
    zone:
      type: dnsZone
      account: ${{ variables.gcpAccount }}
      name: ${{ variables.dnsZone }}

  hooks:
    - when:
        type: deployment
      namespace: ${{ environment.name }}
      labels:
        region: ${{ variables.region }}
      account: ${{ variables.gcpAccount }}
    - when:
        type: ingressRule
      resources:
        dnsRecord:
          type: dnsRecord
          account: ${{ variables.gcpAccount }}
          dnsZone: ${{ environment.resources.zone.id }}
          subdomain: ${{ this.inputs.subdomain }}
          recordType: A
          content: ${{ this.outputs.loadBalancerHostname }}
      dnsZone: ${{ variables.dnsZone }}
      namespace: ${{ environment.name }}
    - when:
        type: service
      namespace: ${{ environment.name }}
      labels:
        region: ${{ variables.region }}
    - account: ${{ variables.gcpAccount }}
      namespace: ${{ environment.name }}
