variables:
  gcpAccount:
    type: arcctlAccount
    description: Name of your registered GCP account.
    provider: gcp
  region:
    type: region
    description: Region to put resources in
    arcctlAccount: ${{ variables.gcpAccount }}
  dnsZone:
    type: string
    description: DNS name for DNS records (ex. architest.dev). The DNS zone must already exist within GCP.

resources:
  vpc:
    type: vpc
    name: ${{ datacenter.name }}-dc
    account: ${{ variables.gcpAccount }}
    region: ${{ variables.region }}

environment:
  hooks:
    - when:
        type: deployment
      namespace: ${{ environment.name }}
      labels:
        region: ${{ variables.region }}
      account: ${{ variables.gcpAccount }}
    - when:
        type: ingressRule
      resources:
        dnsRecord:
          type: dnsRecord
          account: ${{ variables.gcpAccount }}
          dnsZone: ${{ variables.dnsZone }}
          subdomain: ${{ this.inputs.subdomain }}
          recordType: A
          content: ${{ this.outputs.loadBalancerHostname }}
      dnsZone: ${{ variables.dnsZone }}
      namespace: ${{ environment.name }}
    - when:
        type: service
      namespace: ${{ environment.name }}
      labels:
        region: ${{ variables.region }}
    - when:
        type: database
        databaseType: postgres
      resources:
        db-cluster:
          type: databaseCluster
          account: ${{ variables.gcpAccount }}
          name: ${{ this.name }}
          databaseSize: db-f1-micro
          databaseType: ${{ this.inputs.databaseType }}
          databaseVersion: ${{ this.inputs.databaseVersion }}
          region: ${{ variables.region }}
          vpc: ${{ resources.vpc.id }}
      databaseCluster: ${{ this.resources.db-cluster.id }}
      account: ${{ variables.gcpAccount }}
    - account: ${{ variables.gcpAccount }}
      namespace: ${{ environment.name }}
