secrets:
  account: local

variables:
  gcpAccount:
    type: arcctlAccount
    description: Name of your registered GCP account.
    provider: gcp
  region:
    type: region
    description: Region to put resources in
    arcctlAccount: ${{ variables.gcpAccount }}
  # dnsZone:
  #   type: string
  #   description: Name of DNS zone for DNS records

resources:
  vpc:
    type: vpc
    name: gcp-datacenter
    account: ${{ variables.gcpAccount }}
    region: ${{ variables.region }}
  # TODO: Currently all hardcoded, no ingress support, only allows 1 port
  mailslurper:
    type: deployment
    name: mailslurper-function-test
    namespace: ${{ variables.region }}
    account: ${{ variables.gcpAccount }}
    image: docker.io/tyleraldrich/mailslurper:latest
    volume_mounts: []
    exposed_ports:
      - port: 8080
        target_port: 8080
      # - port: 8085
      #   target_port: 8085
    command:
      - sh
      - -c
      - |
        apk update
        apk add wget
        wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        mv jq-linux64 /usr/local/bin/jq
        chmod +x /usr/local/bin/jq
        tmpfile=$(mktemp)
        jq '.wwwPublicURL="http://0.0.0.0:8080" | .servicePublicURL="http://0.0.0.0:8085"' config.json > "$tmpfile"
        mv "$tmpfile" config.json
        ./mailslurper
    # TODO: command wwwPublicURL and servicePublicURL are placeholders

environment:
  # resources:
  #   zone:
  #     type: dnsZone
  #     account: ${{ variables.gcpAccount }}
  #     name: ${{ variables.dnsZone }}
  # hooks:
  #   - when:
  #       type: deployment
  #     namespace: ${{ variables.region }}