name: component-1

static:
  frontend:
    directory: ./frontend/dist
    build:
      context: ./frontend
      command: npm run build
      environment:
        BACKEND_ADDR: ${{ services.api.interfaces.main.ingress.url }}
    ingress:
      subdomain: app
    debug:
      build:
        command: npm start

services:
  api:
    build:
      context: ./backend
    interfaces:
      main:
        port: 8080
        ingress:
          subdomain: api
    environment:
      DB_DSN: ${{ databases.users.url }}

databases:
  users:
    type: postgres:13
