name: test-env

resources:
  vpc:
    type: vpc
    region: nyc1
    name: my-vpc
    provider: do-personal
  dns_zone:
    type: dnsZone
    provider: do-personal
    name: davidthor.me
  cluster:
    type: kubernetesCluster
    region: nyc1
    vpc: ${{ resources.vpc.id }}
    name: my-cluster
    provider: do-personal
    kubernetesVersion: 1.25.4
    nodePools:
      - name: pool-1
        count: 3
        nodeSize: s-1vcpu-2gb

mutators:
  - when:
      type: database
    node:
      provider: do-personal
      inputs:
        vpc: ${{ resources.vpc.id }}
  - when:
      type: dnsRecord
    node:
      provider: do-personal
      inputs:
        dnsZone: ${{ resources.dns_zone.id }}
  - when:
      type: dockerBuild
    node:
      provider: local
      inputs:
        registry: registry.architect.io
        tag: latest
  - node:
      provider: ${{ resources.cluster.provider }}

components:
  architect/component-1:
    source: file:./component-1.yml
