name: Deno CI
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.15.0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install dependencies
        run: npm install
      - name: Compile Windows
        run: deno compile -A --target x86_64-pc-windows-msvc --output ./dist/windows/arcctl main.ts
      - name: Compile Linux
        run: deno compile -A --target x86_64-unknown-linux-gnu --output ./dist/linux/arcctl main.ts
      - name: Compile OSX Amd64
        run: deno compile -A --target x86_64-apple-darwin --output ./dist/osx-amd64/arcctl main.ts
      - name: Compile OSX Arm64
        run: deno compile -A --target aarch64-apple-darwin --output ./dist/osx-arm64/arcctl main.ts
      - name: Release
        run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
