name: Pull requests

on:
  pull_request:
    branches:
      - main

env:
  DENO_DIR: deno_cache

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.34.1
      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - name: Check formatting
        run: deno fmt --check
      - name: Check linting
        run: deno lint
      - name: Run type checks
        run: deno task typecheck
      - name: Run unit tests
        run: deno task test
      - name: Generate coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage.lcov