name: Testing
on:
  push:
    branches-ignore:
      - "main"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.34.1
      - name: Check formatting
        run: deno fmt --check
  # Disabled until existing linting errors are fixed
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup Deno
  #       uses: denolib/setup-deno@master
  #       with:
  #           deno-version: 1.34.1
  #     - name: Check formatting
  #       run: deno lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.34.1
      - name: Run unit tests
        run: deno task test